import { Component, Input, ViewEncapsulation } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import svgs from './svgs.auto-generated';

@Component({
  selector: 'app-icon',
  templateUrl: './icon.component.html',
  styleUrls: ['./icon.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class IconComponent {
  svgString: SafeHtml = '';
  svgName = '';
  @Input()
  set name(name: string) {
    this.svgName = name;
    this.svgString = this.sanitized.bypassSecurityTrustHtml(
      pluckSvg(name, svgs)
    );
  }

  constructor(private sanitized: DomSanitizer) {}
}

function pluckSvg(
  name: string,
  autoGeneratedSVG: { [key: string]: string }
): string {
  return autoGeneratedSVG[name];
}
